import { useEffect, useState } from "react";
import { Link, useLocation } from "wouter";
import Editor from "@monaco-editor/react";
import { Button } from "@/components/ui/button";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { Badge } from "@/components/ui/badge";
import { toast } from "sonner";
import { Check, ChevronRight, Clipboard, Code2, FileCode2, KeyRound, Loader2, Play, RotateCcw, ShieldCheck, Sparkles, Terminal, WandSparkles, X } from "lucide-react";

type Language = "javascript" | "typescript" | "python" | "java" | "go" | "rust" | "html" | "css" | "json" | "sql" | "csharp" | "cpp" | "php" | "ruby" | "kotlin" | "swift";
const languages: Array<{ value: Language; label: string; monaco: string; ext: string }> = [
  ["javascript", "JavaScript", "javascript", "js"], ["typescript", "TypeScript", "typescript", "ts"], ["python", "Python", "python", "py"], ["java", "Java", "java", "java"], ["go", "Go", "go", "go"], ["rust", "Rust", "rust", "rs"], ["html", "HTML", "html", "html"], ["css", "CSS", "css", "css"], ["json", "JSON", "json", "json"], ["sql", "SQL", "sql", "sql"], ["csharp", "C#", "csharp", "cs"], ["cpp", "C++", "cpp", "cpp"], ["php", "PHP", "php", "php"], ["ruby", "Ruby", "ruby", "rb"], ["kotlin", "Kotlin", "kotlin", "kt"], ["swift", "Swift", "swift", "swift"],
].map(([value, label, monaco, ext]) => ({ value: value as Language, label, monaco, ext }));
const starter = `function sumar(a, b) {
  return a + b
}

console.log(sumar(2, 3))`;
type ProviderId = "openai" | "gemini" | "anthropic" | "openrouter" | "ollama";
type ProviderPreset = { id: ProviderId; label: string; hint: string; baseUrl: string; model: string; placeholder: string };
const providerPresets: ProviderPreset[] = [
  { id: "openai", label: "OpenAI · GPT-6 Astra", hint: "API compatible con OpenAI", baseUrl: "https://api.openai.com/v1", model: "gpt-6-astra", placeholder: "sk-..." },
  { id: "gemini", label: "Google Gemini", hint: "API compatible OpenAI de Gemini", baseUrl: "https://generativelanguage.googleapis.com/v1beta/openai", model: "gemini-2.5-flash", placeholder: "AIza..." },
  { id: "anthropic", label: "Anthropic Claude vía OpenRouter", hint: "Claude usando gateway compatible", baseUrl: "https://openrouter.ai/api/v1", model: "anthropic/claude-sonnet-4", placeholder: "sk-or-..." },
  { id: "openrouter", label: "OpenRouter", hint: "Muchos modelos en un endpoint", baseUrl: "https://openrouter.ai/api/v1", model: "openai/gpt-4o-mini", placeholder: "sk-or-..." },
  { id: "ollama", label: "Ollama local", hint: "Modelos locales · sin API key", baseUrl: "http://localhost:11434/v1", model: "llama3.2", placeholder: "ollama (opcional)" },
];
const apiKeyStorage = "codecraft.ai.apiKey";
const baseUrlStorage = "codecraft.ai.baseUrl";
const providerStorage = "codecraft.ai.provider";
const modelStorage = "codecraft.ai.model";

function normalizeBaseUrl(value: string) {
  const trimmed = value.trim().replace(/\/$/, "");
  const parsed = new URL(trimmed);
  const isLocal = parsed.hostname === "localhost" || parsed.hostname === "127.0.0.1";
  if (parsed.protocol !== "https:" && !isLocal) throw new Error("La URL base debe usar HTTPS; HTTP solo está permitido en localhost");
  return trimmed;
}

async function askOpenAI(apiKey: string, baseUrl: string, model: string, language: string, system: string, prompt: string) {
  const endpoint = normalizeBaseUrl(baseUrl);
  const headers: Record<string, string> = { "Content-Type": "application/json" };
  if (apiKey.trim()) headers.Authorization = `Bearer ${apiKey.trim()}`;
  const response = await fetch(`${endpoint}/chat/completions`, { method: "POST", headers, body: JSON.stringify({ model: model.trim(), temperature: 0.25, max_tokens: 3000, messages: [{ role: "system", content: `${system} Lenguaje: ${language}.` }, { role: "user", content: prompt }] }) });
  if (!response.ok) { if (response.status === 401) throw new Error("La API Key no es válida"); if (response.status === 429) throw new Error("OpenAI ha limitado temporalmente la solicitud"); throw new Error(`OpenAI respondió con ${response.status}`); }
  const payload = await response.json() as { choices?: Array<{ message?: { content?: string } }> };
  const result = payload.choices?.[0]?.message?.content?.trim();
  if (!result) throw new Error("OpenAI devolvió una respuesta vacía");
  return result;
}

export default function Home() {
  const [location, setLocation] = useLocation();
  const [code, setCode] = useState(starter); const [prompt, setPrompt] = useState("Crea una función que valide si un correo electrónico es válido"); const [language, setLanguage] = useState<Language>("javascript"); const [reviewResult, setReviewResult] = useState(""); const [correctedResult, setCorrectedResult] = useState(""); const [activeTab, setActiveTab] = useState<"review" | "corrected">("review"); const [provider, setProvider] = useState<ProviderId>("openai"); const [model, setModel] = useState("gpt-6-astra"); const [apiKey, setApiKey] = useState(""); const [baseUrl, setBaseUrl] = useState("https://api.openai.com/v1"); const [showSettings, setShowSettings] = useState(false); const [hasKey, setHasKey] = useState(false); const [busy, setBusy] = useState(false);
  const workspace = location === "/generate" ? "generate" : "review";
  useEffect(() => { const savedProvider = (sessionStorage.getItem(providerStorage) as ProviderId | null) ?? "openai"; const preset = providerPresets.find(item => item.id === savedProvider) ?? providerPresets[0]; const key = sessionStorage.getItem(apiKeyStorage) ?? ""; const base = sessionStorage.getItem(baseUrlStorage) ?? preset.baseUrl; const savedModel = sessionStorage.getItem(modelStorage) ?? preset.model; setProvider(savedProvider); setApiKey(key); setBaseUrl(base); setModel(savedModel); setHasKey(Boolean(key) || savedProvider === "ollama"); }, []);
  const selected = languages.find(item => item.value === language) ?? languages[0]; const result = activeTab === "review" ? reviewResult : correctedResult;
  const saveSettings = () => { if (!apiKey.trim() && provider !== "ollama") return toast.error("Introduce una API Key para continuar"); try { const safeBaseUrl = normalizeBaseUrl(baseUrl || providerPresets[0].baseUrl); if (apiKey.trim()) sessionStorage.setItem(apiKeyStorage, apiKey.trim()); else sessionStorage.removeItem(apiKeyStorage); sessionStorage.setItem(baseUrlStorage, safeBaseUrl); sessionStorage.setItem(providerStorage, provider); sessionStorage.setItem(modelStorage, model.trim()); setBaseUrl(safeBaseUrl); setHasKey(Boolean(apiKey.trim()) || provider === "ollama"); setShowSettings(false); toast.success("Configuración guardada solo durante esta sesión"); } catch (error) { toast.error(error instanceof Error ? error.message : "La URL base no es válida"); } };
  const clearKey = () => { sessionStorage.removeItem(apiKeyStorage); sessionStorage.removeItem(baseUrlStorage); sessionStorage.removeItem(providerStorage); sessionStorage.removeItem(modelStorage); setApiKey(""); setProvider("openai"); setModel("gpt-6-astra"); setBaseUrl("https://api.openai.com/v1"); setHasKey(false); toast.success("Configuración eliminada de esta sesión"); };
  const runReview = async (mode: "review" | "correct") => { if (!code.trim()) return toast.error("Escribe o pega código para empezar"); if (!apiKey.trim() && provider !== "ollama") { setShowSettings(true); return toast.error("Configura tu API Key local primero"); } setBusy(true); try { const system = mode === "review" ? "Analiza el código y responde en español con Markdown usando ## Resumen, ## Hallazgos y ## Recomendaciones. Sé concreto y no reescribas todo." : "Corrige el código y responde en español con Markdown usando ## Versión corregida con el código completo en un único bloque y ## Qué cambió. Conserva la intención y no inventes dependencias."; const answer = await askOpenAI(apiKey, baseUrl, model, language, system, `Revisa este código:\n\n\`\`\`${language}\n${code}\n\`\`\``); if (mode === "correct") { setCorrectedResult(answer); setActiveTab("corrected"); toast.success("Código corregido"); } else { setReviewResult(answer); setActiveTab("review"); toast.success("Revisión lista"); } } catch (error) { toast.error(error instanceof Error ? error.message : "No se pudo completar la solicitud"); } finally { setBusy(false); } };
  const runGenerate = async () => { if (!prompt.trim()) return toast.error("Describe qué quieres construir"); if (!apiKey.trim() && provider !== "ollama") { setShowSettings(true); return toast.error("Configura tu API Key local primero"); } setBusy(true); try { const answer = await askOpenAI(apiKey, baseUrl, model, language, "Genera código funcional, claro y listo para copiar. Devuelve SOLO código, sin Markdown, sin explicaciones y sin bloques de triple backtick.", prompt); setCode(answer.replace(/^```[\\w-]*\\n?/, "").replace(/\\n?```$/, "").trim()); setLocation("/review"); toast.success("Código generado y listo para editar"); } catch (error) { toast.error(error instanceof Error ? error.message : "No se pudo generar el código"); } finally { setBusy(false); } };
  const copyResult = async () => { if (!result) return; await navigator.clipboard.writeText(result); toast.success("Resultado copiado"); }; const reset = () => { setCode(""); setReviewResult(""); setCorrectedResult(""); };

  return <div className="min-h-screen bg-[#f7f8fa] text-[#17202a]"><header className="sticky top-0 z-10 border-b border-[#e6e9ed] bg-white/90 backdrop-blur"><div className="mx-auto flex max-w-[1440px] items-center justify-between px-6 py-4 lg:px-10"><div className="flex items-center gap-3"><div className="grid size-9 place-items-center rounded-xl bg-[#1e3a5f] text-white shadow-sm"><Code2 size={19} /></div><div><div className="font-extrabold tracking-tight">CodeCraft <span className="text-[#e56b42]">Studio</span></div><div className="font-mono text-[10px] uppercase tracking-[.22em] text-[#8090a0]">GitHub Pages edition</div></div></div><div className="flex items-center gap-3"><nav aria-label="Navegación principal" className="hidden items-center gap-1 sm:flex"><Link href="/review" className={`rounded-lg px-3 py-2 text-xs font-bold transition ${workspace === "review" ? "bg-[#eef3f7] text-[#1e3a5f]" : "text-[#718096] hover:bg-[#f6f8fa]"}`}><FileCode2 className="mr-1.5 inline size-3.5" /> Revisar</Link><Link href="/generate" className={`rounded-lg px-3 py-2 text-xs font-bold transition ${workspace === "generate" ? "bg-[#fff0e9] text-[#c8522e]" : "text-[#718096] hover:bg-[#fff8f5]"}`}><WandSparkles className="mr-1.5 inline size-3.5" /> Generar</Link><Link href="/tools" className="rounded-lg px-3 py-2 text-xs font-bold text-[#718096] hover:bg-[#f6f8fa]"><Terminal className="mr-1.5 inline size-3.5" /> Herramientas Linux</Link></nav><span className="hidden items-center gap-2 text-xs text-[#718096] md:flex"><ShieldCheck size={15} className="text-[#4c9f70]" /> Clave local · no se sube</span><Button variant="outline" onClick={() => setShowSettings(true)} className="h-9 border-[#dfe5ea] px-3 text-xs font-bold text-[#34516b]"><KeyRound className="mr-2 size-4" /> {hasKey ? `${providerPresets.find(item => item.id === provider)?.label ?? "IA"} configurado` : "Configurar IA"}</Button></div></div></header>
    {showSettings && <div className="border-b border-[#f2d8cc] bg-[#fffaf7]"><div className="mx-auto flex max-w-[1440px] flex-col gap-4 px-6 py-5 lg:px-10"><div className="flex items-start justify-between"><div><h2 className="text-sm font-bold text-[#324b61]">Conecta tu plataforma de IA</h2><p className="mt-1 max-w-2xl text-xs leading-5 text-[#718096]">Elige OpenAI GPT-6 Astra, Gemini u otra plataforma compatible. La clave se guarda únicamente durante esta sesión y se envía directamente al endpoint elegido; no pasa por CodeCraft ni se publica en GitHub.</p></div><button onClick={() => setShowSettings(false)} className="text-[#9aa7b2] hover:text-[#e56b42]"><X size={18} /></button></div><div className="grid gap-3 md:grid-cols-2"><select value={provider} onChange={e => { const next = providerPresets.find(item => item.id === e.target.value) ?? providerPresets[0]; setProvider(next.id); setBaseUrl(next.baseUrl); setModel(next.model); }} aria-label="Plataforma de IA" className="h-10 rounded-lg border border-[#ead9d1] bg-white px-3 text-sm outline-none focus:border-[#e56b42]">{providerPresets.map(item => <option key={item.id} value={item.id}>{item.label} — {item.hint}</option>)}</select><input value={model} onChange={e => setModel(e.target.value)} placeholder="Identificador del modelo" aria-label="Modelo de IA" className="h-10 rounded-lg border border-[#ead9d1] bg-white px-3 text-sm outline-none focus:border-[#e56b42]"/></div><div className="grid gap-3 md:grid-cols-[1fr_1fr_auto]"><input type="password" value={apiKey} onChange={e => setApiKey(e.target.value)} placeholder={providerPresets.find(item => item.id === provider)?.placeholder ?? "API key"} autoComplete="off" spellCheck={false} aria-label="API Key" className="h-10 rounded-lg border border-[#ead9d1] bg-white px-3 text-sm outline-none focus:border-[#e56b42]"/><input type="url" value={baseUrl} onChange={e => setBaseUrl(e.target.value)} placeholder="https://api.openai.com/v1" autoComplete="url" aria-label="URL base compatible con OpenAI" className="h-10 rounded-lg border border-[#ead9d1] bg-white px-3 text-sm outline-none focus:border-[#e56b42]"/><div className="flex gap-2"><Button onClick={saveSettings} className="h-10 bg-[#e56b42] text-xs font-bold text-white hover:bg-[#d95d35]"><Check className="mr-2 size-4" /> Guardar</Button>{(hasKey || provider === "ollama") && <Button variant="outline" onClick={clearKey} className="h-10 border-[#ead9d1] text-xs text-[#8a98a6]">Eliminar</Button>}</div></div></div></div>}
    <main className="mx-auto max-w-[1440px] px-6 py-8 lg:px-10 lg:py-12"><div className="mb-8 flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><div className="mb-3 flex items-center gap-2 text-xs font-bold uppercase tracking-[.18em] text-[#e56b42]"><Sparkles size={14} /> Espacio de trabajo</div><h1 className="max-w-2xl text-4xl font-extrabold leading-[1.05] tracking-[-.05em] text-[#14283d] md:text-5xl">Código claro. <span className="text-[#e56b42]">Ideas en marcha.</span></h1><p className="mt-4 max-w-xl text-base leading-7 text-[#718096]">Escribe, describe y mejora tu código con OpenAI desde tu propio navegador.</p></div><div className="flex items-center gap-2 text-xs text-[#8a98a6]"><span className={`size-2 rounded-full ${hasKey ? "bg-[#4c9f70]" : "bg-[#e6bb65]"}`} /> {hasKey ? "API Key local activa" : "Falta configurar tu API Key"}</div></div>
      <nav aria-label="Modo de trabajo" className="mb-5 flex max-w-fit gap-1 rounded-xl border border-[#e2e7eb] bg-white p-1 shadow-sm"><Link href="/review" className={`rounded-lg px-4 py-2 text-xs font-bold transition ${workspace === "review" ? "bg-[#1e3a5f] text-white" : "text-[#718096] hover:bg-[#f4f7f9]"}`}><FileCode2 className="mr-2 inline size-4" /> Revisar código</Link><Link href="/generate" className={`rounded-lg px-4 py-2 text-xs font-bold transition ${workspace === "generate" ? "bg-[#e56b42] text-white" : "text-[#718096] hover:bg-[#fff4ef]"}`}><WandSparkles className="mr-2 inline size-4" /> Crear desde texto</Link></nav>
      {workspace === "generate" && <section className="mb-5 rounded-2xl border border-[#f2d8cc] bg-[#fffaf7] p-5 shadow-[0_10px_30px_rgba(229,107,66,.06)]"><div className="mb-3 flex items-center justify-between"><div><h2 className="text-sm font-bold text-[#324b61]">Describe lo que quieres construir</h2><p className="mt-1 text-xs text-[#91a0ad]">La respuesta llegará directamente al editor Monaco.</p></div><Badge className="border-0 bg-[#fff0e9] text-[10px] text-[#c8522e]">Texto → Código</Badge></div><div className="flex flex-col gap-3 md:flex-row"><Textarea value={prompt} onChange={e => setPrompt(e.target.value)} className="min-h-[84px] resize-none border-[#ead9d1] bg-white text-sm" placeholder="Ej.: crea una API REST para..."/><Button onClick={runGenerate} disabled={busy} className="h-11 shrink-0 self-end bg-[#e56b42] px-5 text-xs font-bold text-white hover:bg-[#d95d35] md:self-center">{busy ? <Loader2 className="mr-2 size-4 animate-spin" /> : <Sparkles className="mr-2 size-4" />} Generar código</Button></div></section>}
      <div className="grid gap-5 xl:grid-cols-[1.1fr_.9fr]"><section className="overflow-hidden rounded-2xl border border-[#dde3e9] bg-white shadow-[0_14px_40px_rgba(31,55,78,.06)]"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-[#edf0f3] px-5 py-4"><div className="flex items-center gap-3"><FileCode2 size={18} className="text-[#e56b42]" /><div><h2 className="text-sm font-bold">Tu código</h2><p className="text-xs text-[#91a0ad]">Monaco Editor · resaltado y autocompletado</p></div></div><Select value={language} onValueChange={value => setLanguage(value as Language)}><SelectTrigger className="h-9 w-[155px] border-[#e1e6eb] bg-[#f8fafb] text-xs"><SelectValue /></SelectTrigger><SelectContent>{languages.map(item => <SelectItem key={item.value} value={item.value}>{item.label}</SelectItem>)}</SelectContent></Select></div><div className="bg-[#172635] p-1"><div className="flex items-center gap-2 px-4 py-2 font-mono text-[11px] text-[#8da0b2]"><span className="size-2 rounded-full bg-[#ed8060]" /><span className="size-2 rounded-full bg-[#e6bb65]" /><span className="size-2 rounded-full bg-[#6fb887]" /><span className="ml-2 opacity-60">untitled.{selected.ext}</span></div><Editor height="410px" language={selected.monaco} theme="vs-dark" value={code} onChange={value => setCode(value ?? "")} options={{ minimap: { enabled: false }, fontSize: 13, lineHeight: 21, padding: { top: 12 }, wordWrap: "on", automaticLayout: true, tabSize: 2, scrollBeyondLastLine: false, suggestOnTriggerCharacters: true }} /></div><div className="flex flex-wrap items-center justify-between gap-3 border-t border-[#edf0f3] px-5 py-4"><button onClick={reset} className="flex items-center gap-2 text-xs font-semibold text-[#8a98a6] transition hover:text-[#e56b42]"><RotateCcw size={14} /> Limpiar</button><div className="flex gap-2"><Button variant="outline" onClick={() => runReview("review")} disabled={busy} className="h-10 border-[#dfe5ea] px-4 text-xs font-bold text-[#34516b] hover:bg-[#f5f8fa]">{busy ? <Loader2 className="mr-2 size-4 animate-spin" /> : <Play className="mr-2 size-4" />} Revisar código</Button><Button onClick={() => runReview("correct")} disabled={busy} className="h-10 bg-[#e56b42] px-4 text-xs font-bold text-white hover:bg-[#d95d35]"><WandSparkles className="mr-2 size-4" /> Corregir con IA</Button></div></div></section>
      <section className="overflow-hidden rounded-2xl border border-[#dde3e9] bg-white shadow-[0_14px_40px_rgba(31,55,78,.06)]"><div className="flex items-center justify-between border-b border-[#edf0f3] px-5 py-4"><div><h2 className="text-sm font-bold">Resultado</h2><p className="text-xs text-[#91a0ad]">Análisis y sugerencias accionables</p></div>{result && <button onClick={copyResult} className="flex items-center gap-2 text-xs font-semibold text-[#6c7f8d] hover:text-[#e56b42]"><Clipboard size={14} /> Copiar</button>}</div><div className="flex gap-6 border-b border-[#edf0f3] px-5"><button onClick={() => setActiveTab("review")} className={`relative py-3 text-xs font-bold ${activeTab === "review" ? "text-[#e56b42]" : "text-[#9aa7b2]"}`}>Revisión {activeTab === "review" && <span className="absolute inset-x-0 bottom-0 h-0.5 bg-[#e56b42]" />}</button><button onClick={() => setActiveTab("corrected")} className={`relative py-3 text-xs font-bold ${activeTab === "corrected" ? "text-[#e56b42]" : "text-[#9aa7b2]"}`}>Versión corregida {activeTab === "corrected" && <span className="absolute inset-x-0 bottom-0 h-0.5 bg-[#e56b42]" />}</button></div><div aria-live="polite" className="min-h-[410px] overflow-auto p-6">{result ? <div className="whitespace-pre-wrap font-mono text-[12px] leading-6 text-[#435669]">{result}</div> : <div className="flex min-h-[360px] flex-col items-center justify-center text-center"><div className="mb-5 grid size-14 place-items-center rounded-2xl bg-[#fff3ee] text-[#e56b42]"><WandSparkles size={24} /></div><h3 className="text-sm font-bold text-[#324b61]">{activeTab === "review" ? "Tu análisis aparecerá aquí" : "Tu versión corregida aparecerá aquí"}</h3><p className="mt-2 max-w-[250px] text-xs leading-5 text-[#99a7b2]">Configura tu clave y selecciona una acción para empezar.</p><div className="mt-6 flex flex-wrap justify-center gap-2"><Badge variant="outline" className="border-[#e3e8ed] text-[10px] font-medium text-[#7d8e9c]">Errores</Badge><Badge variant="outline" className="border-[#e3e8ed] text-[10px] font-medium text-[#7d8e9c]">Rendimiento</Badge><Badge variant="outline" className="border-[#e3e8ed] text-[10px] font-medium text-[#7d8e9c]">Buenas prácticas</Badge></div></div>}</div></section></div>
      <div className="mt-6 grid gap-3 sm:grid-cols-3"><div className="rounded-xl border border-[#e8ecef] bg-white px-4 py-3"><div className="mb-1 text-[10px] font-bold uppercase tracking-[.15em] text-[#9aa7b2]">01 · Escribe</div><div className="text-xs font-semibold text-[#476176]">Monaco con resaltado</div></div><div className="rounded-xl border border-[#e8ecef] bg-white px-4 py-3"><div className="mb-1 text-[10px] font-bold uppercase tracking-[.15em] text-[#9aa7b2]">02 · Describe</div><div className="text-xs font-semibold text-[#476176]">Pasa de texto a código</div></div><div className="rounded-xl border border-[#e8ecef] bg-white px-4 py-3"><div className="mb-1 text-[10px] font-bold uppercase tracking-[.15em] text-[#9aa7b2]">03 · Mejora</div><div className="flex items-center gap-1 text-xs font-semibold text-[#476176]">Revisa con confianza <ChevronRight size={14} className="text-[#e56b42]" /></div></div></div>
    </main><footer className="mx-auto max-w-[1440px] px-6 pb-8 pt-2 text-center text-[11px] text-[#9aa7b2] lg:px-10">CodeCraft Studio · GitHub Pages · La API Key permanece solo durante tu sesión.</footer></div>;
}
